# golangci-lint configuration for Alec project
# Based on constitutional requirements for code quality

run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters-settings:
  gocyclo:
    # Constitutional requirement: Cyclomatic complexity limited to 10
    min-complexity: 10

  funlen:
    # Constitutional requirement: No functions exceeding 50 lines
    lines: 50
    statements: 40

  goimports:
    local-prefixes: github.com/your-org/alec

  govet:
    enable-all: true

  revive:
    min-confidence: 0

  staticcheck:
    go: "1.21"

linters:
  enable:
    - bodyclose
    - dogsled
    - dupl
    - errcheck
    - exportloopref
    - exhaustive
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - prealloc
    - revive
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace

  disable:
    - deadcode    # deprecated
    - varcheck    # deprecated
    - structcheck # deprecated

issues:
  exclude-rules:
    # Allow long lines in generated files
    - path: ".*\\.pb\\.go"
      linters:
        - lll

    # Allow complexity in test files
    - path: ".*_test\\.go"
      linters:
        - gocyclo
        - funlen

    # Allow long functions in main.go for CLI setup
    - path: "cmd/alec/main\\.go"
      linters:
        - funlen

  max-issues-per-linter: 50
  max-same-issues: 3