# GoReleaser configuration for Alec
# This configuration automates building, packaging, and releasing
# Supports macOS (Intel and Apple Silicon) and Homebrew tap integration

version: 2

before:
  hooks:
    # Ensure dependencies are up to date
    - go mod tidy
    # Run unit and contract tests before building (skip integration tests)
    - go test ./tests/unit ./tests/contract ./tests

builds:
  - id: alec
    binary: alec
    main: ./cmd/alec
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
      - -X main.builtBy=goreleaser

archives:
  - id: alec-archive
    format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "arm64" }}aarch64
      {{- else }}{{ .Arch }}{{ end }}
    files:
      - LICENSE*
      - README*
      - CHANGELOG*

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - 'merge conflict'
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: 'Bug fixes'
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: 'Performance improvements'
      regexp: '^.*?perf(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: 'Refactors'
      regexp: '^.*?refactor(\([[:word:]]+\))??!?:.+$'
      order: 3
    - title: Others
      order: 999

brews:
  - name: alec
    repository:
      owner: shaiu
      name: homebrew-alec
      token: "{{ .Env.GITHUB_TOKEN }}"
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    homepage: "https://github.com/shaiu/alec"
    description: "Terminal UI for organizing and executing scripts without CLI maintenance overhead"
    license: "MIT"
    directory: Formula
    install: |
      bin.install "alec"
    test: |
      system "#{bin}/alec", "--version"

release:
  github:
    owner: shaiu
    name: alec
  draft: false
  prerelease: auto
  name_template: "{{.ProjectName}}-v{{.Version}}"
  footer: |
    ## Installation

    ### Homebrew (macOS)
    ```bash
    brew tap shaiu/alec
    brew install alec
    ```

    ### Direct Download
    Download the appropriate binary for your system from the assets below.

    ---

    **Full Changelog**: https://github.com/shaiu/alec/compare/{{ .PreviousTag }}...{{ .Tag }}
